In [19]:
import pandas as pd

df = pd.read_csv(
    "../api_pipeline/researchmate_25_queries.csv"
)

df.head()

,query,source,source_id,title,authors,abstract,keywords,year,doi,url
0,machine learning healthcare,PubMed,42876421,Bionic Structural Design of Multifunctional Flexible Polypyrrole Sensors for Human Health Monitoring.,"['Mingqian Sheng', 'Mingyang Qiu', 'Enchong Ning', 'Zhuoyu Yang', 'Junlin Wang', 'Qinyan Liu', 'Yanling Tan', 'Min Liao', 'Bitao Liu', 'Lingling Peng', 'Wenbo Chen', 'Tong Feng', 'Huijian Liu', 'Zhongyan Gao']","Rehabilitation medicine is an essential component of universal health coverage, while emerging electronic skin offers new opportunities for portable and personalized healthcare. However, flexible pressure sensors still face trade-offs among sensitivity, detection range, and stability, and gas sensors remain challenged by low-concentration detection and environmental robustness. Herein, a biomimetic ""Thalia dealbata"" microstructured hydrophobic polypyrrole/polydimethylsiloxane (S@PPy/PDMS) composite sensor was fabricated through a one-step template method and controllable in situ polymerization. The biomimetic PDMS microstructure enhances pressure response, while conductive and NH3-sensitive PPy enables dual-mode pressure and gas sensing on a single flexible platform. The sensor exhibits a wide pressure range of 0-25 kPa, a high sensitivity of 3.617 kPa- 1, and excellent durability over 19 500 compression-release cycles. It also detects NH3 concentrations as low as 1 ppm with stable performance over 60 days. The dual-functional sensor enables complementary monitoring of mechanical physiological signals, including respiration, pulse, and body motion, together with metabolic information from exhaled NH3. A five-channel sensor array further decodes numerical gestures with 100% accuracy via machine learning and wireless communication. Integrating respiratory mechanical sensing with exhaled NH3 detection, this platform offers potential for longitudinal, noninvasive multiparametric monitoring, particularly for CKD assessment, human-machine interfaces, smart wearables, assistive technologies, and telemedicine.","['CKD', 'electronic skin', 'machine learning', 'medical healthcare']",2026.0,10.1002/smtd.71134,https://pubmed.ncbi.nlm.nih.gov/42876421/
1,machine learning healthcare,PubMed,42876358,Clinical Decision Support Models to Optimize Controlled Ovarian Hyperstimulation: A Scoping Review.,"['Robin Z Y Lu', 'Toni J F Michael', 'Vinayak Smith', 'Beverley J Vollenhoven', 'Sophie L Stocker']","Controlled ovarian hyperstimulation (COH) is a precision medicine challenge, with substantial inter-individual variability in ovarian response affecting treatment efficacy and safety during in vitro fertilization (IVF). Clinical decision support (CDS) tools incorporating statistical, machine learning, and artificial intelligence approaches have been developed to individualize gonadotropin dosing and ovulation trigger timing. Therefore, this study aims to identify and evaluate CDS tools informing prescribing decisions during COH. Following PRISMA-ScR guidance, Embase, MEDLINE, PubMed, and Scopus were searched from inception to March 2026. Studies evaluating CDS tools informing COH dosing and/or ovulation trigger timing during IVF were included, stratified by predictive domain and analyzed descriptively. Primary outcomes were oocyte yield and metaphase II (MII) oocyte yield. Secondary outcomes included gonadotropin use and pregnancy-related outcomes. Of 2879 records identified, five studies (n = 16,441) were included. One study reported precision-dosing CDS tools that were associated with increased MII oocyte yield (1.5 oocytes, p < 0.001) and reduced gonadotropin use (195 IU, p < 0.001) compared with clinician-directed dosing. A trigger-timing model improved MII oocyte yield (2.5 oocytes, p < 0.01), whereas combined dosing-and-trigger models demonstrated inconsistent effects. K-nearest neighbor (n = 3) and linear regression (n = 3) approaches predominated. No pregnancy-related outcomes were reported. No clinically evaluated mechanistic pharmacokinetic/pharmacodynamic models were identified. CDS tools show promise for individualizing COH and improving treatment efficiency through precision dosing. However, clinical translation remains limited by a small and heterogeneous evidence base, reliance on surrogate outcomes, and lack of mechanistic model-informed approaches. Prospective studies evaluating clinically meaningful outcomes are required to establish the role of CDS tools in personalized reproductive medicine.","['clinical decision support', 'controlled ovarian hyperstimulation', 'gonadotropin', 'in vitro fertilization', 'machine learning', 'ovulation trigger', 'precision dosing', 'scoping review']",2026.0,10.1111/cts.70742,https://pubmed.ncbi.nlm.nih.gov/42876358/
2,machine learning healthcare,PubMed,42876042,Machine learning predictors of post-radiotherapy cardiotoxicity in a Latin American breast cancer cohort: Clinical risk factors outperform cardiac dosimetry.,"['Víctor Aguirre-Bravo', 'Rodrigo El Far', 'María Herrera Ruiz', 'Sophia Gálvez Santelices', 'Pablo Munoz-Schuffenegger', 'Tomás Merino', 'Sergio Diez Domingo', 'Marcelo E Andia']","BACKGROUND: Most evidence on post-radiotherapy cardiotoxicity (CDT) derives from Global North cohorts, and the relative contribution of baseline clinical risk versus cardiac dosimetry remains poorly characterized in Latin American populations. PURPOSE: To examine, in a Chilean breast cancer cohort, whether baseline clinical risk factors or cardiac dose-volume metrics better predict post-RT cardiac events, using supervised and unsupervised learning. METHODS: Retrospective cohort of 42 breast cancer patients treated with thoracic radiotherapy (RT, median heart dose 2.6 Gy; median follow-up 84.4 months). CDT was defined per CTCAE v5.0 ( ≥ Grade 1), excluding Grade 1 events coded under the non-specific term ""Cardiac disorders - Other, specify"", which on review were incidental imaging findings. Dose-volume histogram (DVH) parameters from seven cardiac substructures were extracted. Firth penalized logistic regression was used for prediction, principal component analysis (PCA) and kernel PCA for exploratory clustering, and bootstrap 0.632+ for optimism correction. The 2023 American Heart Association (AHA) PREVENT score was evaluated post hoc. RESULTS: Ten patients (23.8%) developed CDT and 16 (38.1%) experienced cardiovascular events. No DVH differences were found between CDT+ and CDT- groups across any cardiac structure (all p > 0.05 ), although the design is powered only for large effects. By contrast, IMRT delivered significantly higher cardiac doses than 3D-CRT across multiple substructures, without a differential CDT rate. Pre-existing cardiovascular disease was the strongest predictor (crude OR = 6.50, p = 0.020 ; adjusted OR = 2.08, 95% CI 1.03-4.16, p = 0.040 ). The median time to the first CTCAE-graded event was 48.4 months. The clinical-only model reached an area under the curve (AUC) of 0.783 versus 0.604 for dosimetry alone; the combined model corrected to 0.649 (95% CI 0.204-0.933). The AHA PREVENT score showed no significant risk gradient (trend p = 0.203 ) but was markedly less susceptible to overfitting than DVH-only models (optimism 0.089 vs. 0.194). CONCLUSIONS: In this low-cardiac-dose cohort, baseline clinical variables outperformed cardiac dose-volume metrics in predicting post-RT cardiac events, although the design was not powered to exclude a dose-effect relationship at these exposures. Registry-based baseline risk assessment is therefore the more robust starting point in this setting, and IMRT breast RT planning warrants multi-substructure cardiac dosimetry monitoring.","['AHA PREVENT score', 'Firth logistic regression', 'Latin America', 'breast cancer radiotherapy', 'cardiac dosimetry', 'cardio‐oncology', 'machine learning', 'post‐radiotherapy cardiotoxicity']",2026.0,10.1002/acm2.70862,https://pubmed.ncbi.nlm.nih.gov/42876042/
3,machine learning healthcare,PubMed,42875776,Mismatch between urban eco-sanitation improvement and health service supply capacity: evidence from Chinese city panel data and interpretable machine learning.,"['Zhen Peng', 'Lin Wang']","BACKGROUND: Health service supply capacity depends not only on medical resource stocks but also on urban eco-sanitation conditions and resource-allocation mechanisms. Existing studies focus mainly on environmental exposure and health outcomes, with limited attention to whether eco-sanitation improvements can be converted into health service supply capacity. METHODS: This study constructed a panel of Chinese prefecture-level and above cities for 2002-2024, using the health service supply capacity index as the dependent variable and the eco-sanitation environment index as the core explanatory variable. Two-way fixed effects models, dimension-specific analysis, mechanism tests, heterogeneity analysis, robustness checks, and interpretable machine learning identified mismatch mechanisms and boundary conditions. The mechanism analysis was extended to two- and three-year ESE lags and one- and two-year lagged investment variables. Carbon-emission comparability was reassessed on exact CEADs-matched samples for 2002-2019. Hu Huanyong line subgroup models were additionally estimated with city and province-year fixed effects. RESULTS: The eco-sanitation environment, green infrastructure, and municipal sanitation facilities improved continuously, whereas health service supply capacity increased more slowly. The baseline model does not support a stable positive conversion from eco-sanitation improvement to stronger supply capacity. Dimension-specific results reveal differentiated roles. The positive PPI coefficient must not be read as a pollution benefit; it is consistent with a demand-induced or compensatory resource-allocation response. Neither two- to three-year ESE lags nor one- to two-year lagged investment variables produced a stable urban construction investment transmission chain. The positive CEADs interaction was confirmed only within the 2002-2019 matched sample and therefore represents pre-pandemic evidence. The southeastern Hu-line coefficient attenuated and lost conventional significance after province-year policy shocks were absorbed. Machine learning indicates the relationship is shaped by development stage, population size, fiscal capacity, and nonlinear boundaries. CONCLUSIONS: Eco-sanitation improvement is not a sufficient condition for enhancing health service supply capacity. Healthy city development should integrate eco-sanitation governance, infrastructure investment, workforce allocation, and fiscal arrangements into a unified governance framework. Because HSC is a supply-side proxy based on resource counts, these implications concern resource availability and network density rather than quality of care, realized utilization, accessibility, or overall health-system performance.","['Chinese cities', 'Health service governance', 'Health service supply capacity', 'Healthcare resource allocation', 'Interpretable machine learning', 'Urban eco-sanitation environment']",2026.0,10.1186/s12913-026-15444-8,https://pubmed.ncbi.nlm.nih.gov/42875776/
4,machine learning healthcare,PubMed,42875668,Predicting Hospital-associated complications in older adults: methodological considerations.,"['Shukhrat Valiev', 'Dilnavoz Yuldasheva', 'Malika Khojimatova', 'Dilorom Saidova', 'Shaxlo R Sodiqova', 'Nizom Ermatov', 'Zeynab Afzali']","Machine learning is increasingly used to predict post-surgical complications, but predictive performance does not guarantee clinical readiness. Shimizu and colleagues developed a promising model for older adults undergoing tibial fracture surgery using a large Japanese database. However, four methodological pitfalls warrant attention. First, the composite outcome was not validated in this population, and excluding in-hospital deaths introduced survivorship bias, underestimating the true burden of severe complications. Second, days to surgery, a variable not known at admission, created target leakage that inflates performance and undermines the admission-time claim. Third, using the test set for feature selection violated TRIPOD guidelines and likely overstated the scorecard's utility. Fourth, the Super Learner exhibited substantial overfitting, with a 0.110 drop between training (AUC = 0.850) and test (AUC = 0.740) performance, while offering only marginal improvement over simpler models. We suggest redeveloping the model with proper internal validation, excluding leakage-prone predictors, treating death as a competing risk, and prioritizing interpretability when complex ensembles offer limited added value. External validation remains essential before clinical implementation.","['Data leakage', 'Machine learning', 'Post-surgical complications', 'Prediction modeling']",2026.0,10.1007/s40520-026-03507-z,https://pubmed.ncbi.nlm.nih.gov/42875668/

In [20]:
df.shape

(340, 10)

In [21]:
df.columns

Index(['query', 'source', 'source_id', 'title', 'authors', 'abstract',
       'keywords', 'year', 'doi', 'url'],
      dtype='str')

In [22]:
df["source"].value_counts()

source
PubMed      125
Crossref    125
arXiv        90
Name: count, dtype: int64

In [23]:
df.isna().sum()

query          0
source         0
source_id      0
title          1
authors        0
abstract     111
keywords       0
year          21
doi           66
url            0
dtype: int64

In [24]:
print("Exact duplicate rows:", df.duplicated().sum())

print(
    "Duplicate DOI values:",
    df["doi"].dropna().duplicated().sum()
)

print(
    "Duplicate titles:",
    df["title"].dropna().duplicated().sum()
)

Exact duplicate rows: 0
Duplicate DOI values: 1
Duplicate titles: 7

In [25]:
df.dtypes

query            str
source           str
source_id        str
title            str
authors          str
abstract         str
keywords         str
year         float64
doi              str
url              str
dtype: object

In [26]:
pd.set_option("display.max_colwidth", None)

df[
    [
        "query",
        "source",
        "title",
        "abstract",
        "keywords",
        "year",
        "doi"
    ]
].head(10)

,query,source,title,abstract,keywords,year,doi
0,machine learning healthcare,PubMed,Bionic Structural Design of Multifunctional Flexible Polypyrrole Sensors for Human Health Monitoring.,"Rehabilitation medicine is an essential component of universal health coverage, while emerging electronic skin offers new opportunities for portable and personalized healthcare. However, flexible pressure sensors still face trade-offs among sensitivity, detection range, and stability, and gas sensors remain challenged by low-concentration detection and environmental robustness. Herein, a biomimetic ""Thalia dealbata"" microstructured hydrophobic polypyrrole/polydimethylsiloxane (S@PPy/PDMS) composite sensor was fabricated through a one-step template method and controllable in situ polymerization. The biomimetic PDMS microstructure enhances pressure response, while conductive and NH3-sensitive PPy enables dual-mode pressure and gas sensing on a single flexible platform. The sensor exhibits a wide pressure range of 0-25 kPa, a high sensitivity of 3.617 kPa- 1, and excellent durability over 19 500 compression-release cycles. It also detects NH3 concentrations as low as 1 ppm with stable performance over 60 days. The dual-functional sensor enables complementary monitoring of mechanical physiological signals, including respiration, pulse, and body motion, together with metabolic information from exhaled NH3. A five-channel sensor array further decodes numerical gestures with 100% accuracy via machine learning and wireless communication. Integrating respiratory mechanical sensing with exhaled NH3 detection, this platform offers potential for longitudinal, noninvasive multiparametric monitoring, particularly for CKD assessment, human-machine interfaces, smart wearables, assistive technologies, and telemedicine.","['CKD', 'electronic skin', 'machine learning', 'medical healthcare']",2026.0,10.1002/smtd.71134
1,machine learning healthcare,PubMed,Clinical Decision Support Models to Optimize Controlled Ovarian Hyperstimulation: A Scoping Review.,"Controlled ovarian hyperstimulation (COH) is a precision medicine challenge, with substantial inter-individual variability in ovarian response affecting treatment efficacy and safety during in vitro fertilization (IVF). Clinical decision support (CDS) tools incorporating statistical, machine learning, and artificial intelligence approaches have been developed to individualize gonadotropin dosing and ovulation trigger timing. Therefore, this study aims to identify and evaluate CDS tools informing prescribing decisions during COH. Following PRISMA-ScR guidance, Embase, MEDLINE, PubMed, and Scopus were searched from inception to March 2026. Studies evaluating CDS tools informing COH dosing and/or ovulation trigger timing during IVF were included, stratified by predictive domain and analyzed descriptively. Primary outcomes were oocyte yield and metaphase II (MII) oocyte yield. Secondary outcomes included gonadotropin use and pregnancy-related outcomes. Of 2879 records identified, five studies (n = 16,441) were included. One study reported precision-dosing CDS tools that were associated with increased MII oocyte yield (1.5 oocytes, p < 0.001) and reduced gonadotropin use (195 IU, p < 0.001) compared with clinician-directed dosing. A trigger-timing model improved MII oocyte yield (2.5 oocytes, p < 0.01), whereas combined dosing-and-trigger models demonstrated inconsistent effects. K-nearest neighbor (n = 3) and linear regression (n = 3) approaches predominated. No pregnancy-related outcomes were reported. No clinically evaluated mechanistic pharmacokinetic/pharmacodynamic models were identified. CDS tools show promise for individualizing COH and improving treatment efficiency through precision dosing. However, clinical translation remains limited by a small and heterogeneous evidence base, reliance on surrogate outcomes, and lack of mechanistic model-informed approaches. Prospective studies evaluating clinically meaningful outcomes are required to establish the role of CDS tools in personalized reproductive medicine.","['clinical decision support', 'controlled ovarian hyperstimulation', 'gonadotropin', 'in vitro fertilization', 'machine learning', 'ovulation trigger', 'precision dosing', 'scoping review']",2026.0,10.1111/cts.70742
2,machine learning healthcare,PubMed,Machine learning predictors of post-radiotherapy cardiotoxicity in a Latin American breast cancer cohort: Clinical risk factors outperform cardiac dosimetry.,"BACKGROUND: Most evidence on post-radiotherapy cardiotoxicity (CDT) derives from Global North cohorts, and the relative contribution of baseline clinical risk versus cardiac dosimetry remains poorly characterized in Latin American populations. PURPOSE: To examine, in a Chilean breast cancer cohort, whether baseline clinical risk factors or cardiac dose-volume metrics better predict post-RT cardiac events, using supervised and unsupervised learning. METHODS: Retrospective cohort of 42 breast cancer patients treated with thoracic radiotherapy (RT, median heart dose 2.6 Gy; median follow-up 84.4 months). CDT was defined per CTCAE v5.0 ( ≥ Grade 1), excluding Grade 1 events coded under the non-specific term ""Cardiac disorders - Other, specify"", which on review were incidental imaging findings. Dose-volume histogram (DVH) parameters from seven cardiac substructures were extracted. Firth penalized logistic regression was used for prediction, principal component analysis (PCA) and kernel PCA for exploratory clustering, and bootstrap 0.632+ for optimism correction. The 2023 American Heart Association (AHA) PREVENT score was evaluated post hoc. RESULTS: Ten patients (23.8%) developed CDT and 16 (38.1%) experienced cardiovascular events. No DVH differences were found between CDT+ and CDT- groups across any cardiac structure (all p > 0.05 ), although the design is powered only for large effects. By contrast, IMRT delivered significantly higher cardiac doses than 3D-CRT across multiple substructures, without a differential CDT rate. Pre-existing cardiovascular disease was the strongest predictor (crude OR = 6.50, p = 0.020 ; adjusted OR = 2.08, 95% CI 1.03-4.16, p = 0.040 ). The median time to the first CTCAE-graded event was 48.4 months. The clinical-only model reached an area under the curve (AUC) of 0.783 versus 0.604 for dosimetry alone; the combined model corrected to 0.649 (95% CI 0.204-0.933). The AHA PREVENT score showed no significant risk gradient (trend p = 0.203 ) but was markedly less susceptible to overfitting than DVH-only models (optimism 0.089 vs. 0.194). CONCLUSIONS: In this low-cardiac-dose cohort, baseline clinical variables outperformed cardiac dose-volume metrics in predicting post-RT cardiac events, although the design was not powered to exclude a dose-effect relationship at these exposures. Registry-based baseline risk assessment is therefore the more robust starting point in this setting, and IMRT breast RT planning warrants multi-substructure cardiac dosimetry monitoring.","['AHA PREVENT score', 'Firth logistic regression', 'Latin America', 'breast cancer radiotherapy', 'cardiac dosimetry', 'cardio‐oncology', 'machine learning', 'post‐radiotherapy cardiotoxicity']",2026.0,10.1002/acm2.70862
3,machine learning healthcare,PubMed,Mismatch between urban eco-sanitation improvement and health service supply capacity: evidence from Chinese city panel data and interpretable machine learning.,"BACKGROUND: Health service supply capacity depends not only on medical resource stocks but also on urban eco-sanitation conditions and resource-allocation mechanisms. Existing studies focus mainly on environmental exposure and health outcomes, with limited attention to whether eco-sanitation improvements can be converted into health service supply capacity. METHODS: This study constructed a panel of Chinese prefecture-level and above cities for 2002-2024, using the health service supply capacity index as the dependent variable and the eco-sanitation environment index as the core explanatory variable. Two-way fixed effects models, dimension-specific analysis, mechanism tests, heterogeneity analysis, robustness checks, and interpretable machine learning identified mismatch mechanisms and boundary conditions. The mechanism analysis was extended to two- and three-year ESE lags and one- and two-year lagged investment variables. Carbon-emission comparability was reassessed on exact CEADs-matched samples for 2002-2019. Hu Huanyong line subgroup models were additionally estimated with city and province-year fixed effects. RESULTS: The eco-sanitation environment, green infrastructure, and municipal sanitation facilities improved continuously, whereas health service supply capacity increased more slowly. The baseline model does not support a stable positive conversion from eco-sanitation improvement to stronger supply capacity. Dimension-specific results reveal differentiated roles. The positive PPI coefficient must not be read as a pollution benefit; it is consistent with a demand-induced or compensatory resource-allocation response. Neither two- to three-year ESE lags nor one- to two-year lagged investment variables produced a stable urban construction investment transmission chain. The positive CEADs interaction was confirmed only within the 2002-2019 matched sample and therefore represents pre-pandemic evidence. The southeastern Hu-line coefficient attenuated and lost conventional significance after province-year policy shocks were absorbed. Machine learning indicates the relationship is shaped by development stage, population size, fiscal capacity, and nonlinear boundaries. CONCLUSIONS: Eco-sanitation improvement is not a sufficient condition for enhancing health service supply capacity. Healthy city development should integrate eco-sanitation governance, infrastructure investment, workforce allocation, and fiscal arrangements into a unified governance framework. Because HSC is a supply-side proxy based on resource counts, these implications concern resource availability and network density rather than quality of care, realized utilization, accessibility, or overall health-system performance.","['Chinese cities', 'Health service governance', 'Health service supply capacity', 'Healthcare resource allocation', 'Interpretable machine learning', 'Urban eco-sanitation environment']",2026.0,10.1186/s12913-026-15444-8
4,machine learning healthcare,PubMed,Predicting Hospital-associated complications in older adults: methodological considerations.,"Machine learning is increasingly used to predict post-surgical complications, but predictive performance does not guarantee clinical readiness. Shimizu and colleagues developed a promising model for older adults undergoing tibial fracture surgery using a large Japanese database. However, four methodological pitfalls warrant attention. First, the composite outcome was not validated in this population, and excluding in-hospital deaths introduced survivorship bias, underestimating the true burden of severe complications. Second, days to surgery, a variable not known at admission, created target leakage that inflates performance and undermines the admission-time claim. Third, using the test set for feature selection violated TRIPOD guidelines and likely overstated the scorecard's utility. Fourth, the Super Learner exhibited substantial overfitting, with a 0.110 drop between training (AUC = 0.850) and test (AUC = 0.740) performance, while offering only marginal improvement over simpler models. We suggest redeveloping the model with proper internal validation, excluding leakage-prone predictors, treating death as a competing risk, and prioritizing interpretability when complex ensembles offer limited added value. External validation remains essential before clinical implementation.","['Data leakage', 'Machine learning', 'Post-surgical complications', 'Prediction modeling']",2026.0,10.1007/s40520-026-03507-z
5,machine learning healthcare,arXiv,Review of Interpretable Machine Learning Models for Disease Prognosis,"In response to the COVID-19 pandemic, the integration of interpretable machine learning techniques has garnered significant attention, offering transparent and understandable insights crucial for informed clinical decision making. This literature review delves into the applications of interpretable machine learning in predicting the prognosis of respiratory diseases, particularly focusing on COVID-19 and its implications for future research and clinical practice. We reviewed various machine learning models that are not only capable of incorporating existing clinical domain knowledge but also have the learning capability to explore new information from the data. These models and experiences not only aid in managing the current crisis but also hold promise for addressing future disease outbreaks. By harnessing interpretable machine learning, healthcare systems can enhance their preparedness and response capabilities, thereby improving patient outcomes and mitigating the impact of respiratory diseases in the years to come.",['cs.LG'],2024.0,NaN
6,machine learning healthcare,arXiv,A Comprehensive Guide to Differential Privacy: From Theory to User Expectations,"The increasing availability of personal data has enabled significant advances in fields such as machine learning, healthcare, and cybersecurity. However, this data abundance also raises serious privacy concerns, especially in light of powerful re-identification attacks and growing legal and ethical demands for responsible data use. Differential privacy (DP) has emerged as a principled, mathematically grounded framework for mitigating these risks. This review provides a comprehensive survey of DP, covering its theoretical foundations, practical mechanisms, and real-world applications. It explores key algorithmic tools and domain-specific challenges - particularly in privacy-preserving machine learning and synthetic data generation. The report also highlights usability issues and the need for improved communication and transparency in DP systems. Overall, the goal is to support informed adoption of DP by researchers and practitioners navigating the evolving landscape of data privacy.","['cs.CR', 'cs.AI', 'cs.LG']",2025.0,NaN
7,machine learning healthcare,arXiv,Cognizance of Post-COVID-19 Multi-Organ Dysfunction through Machine Learning Analysis,"In the year 2022, a total of 466 patients from various cities across Iraq were included in this study. This research paper focuses on the application of machine learning techniques to analyse and predict multi-organ dysfunction in individuals experiencing Post-COVID-19 Syndrome, commonly known as Long COVID. Post-COVID-19 Syndrome presents a wide array of persistent symptoms affecting various organ systems, posing a significant challenge to healthcare. Leveraging the power of artificial intelligence, this study aims to enhance early detection and management of this complex condition. The paper outlines the importance of data collection and preprocessing, feature selection and engineering, model development and validation, and ethical considerations in conducting research in this field. By improving our understanding of Post-COVID-19 Syndrome through machine learning, healthcare providers can identify at-risk individuals and offer timely interventions, potentially improving patient outcomes and quality of life. Further research is essential to refine models, validate their clinical utility, and explore treatment options for Long COVID. Keywords: Post-COVID-19 Syndrome, Machine Learning, Multi-Organ Dysfunction, Healthcare, Artificial Intelligence.","['cs.LG', 'q-bio.OT']",2023.0,NaN
8,machine learning healthcare,arXiv,Nonparametric Universal Copula Modeling,"To handle the ubiquitous problem of ""dependence learning,"" copulas are quickly becoming a pervasive tool across a wide range of data-driven disciplines encompassing neuroscience, finance, econometrics, genomics, social science, machine learning, healthcare and many more. Copula (or connection) functions were invented in 1959 by Abe Sklar in response to a query of Maurice Frechet. After 60 years, where do we stand now? This article provides a history of the key developments and offers a unified perspective.","['stat.ME', 'stat.AP', 'stat.CO']",2019.0,NaN
9,machine learning healthcare,arXiv,A Parallel Sparse Tensor Benchmark Suite on CPUs and GPUs,"Tensor computations present significant performance challenges that impact a wide spectrum of applications ranging from machine learning, healthcare analytics, social network analysis, data mining to quantum chemistry and signal processing. Efforts to improve the performance of tensor computations include exploring data layout, execution scheduling, and parallelism in common tensor kernels. This work presents a benchmark suite for arbitrary-order sparse tensor kernels using state-of-the-art tensor formats: coordinate (COO) and hierarchical coordinate (HiCOO) on CPUs and GPUs. It presents a set of reference tensor kernel implementations that are compatible with real-world tensors and power law tensors extended from synthetic graph generation techniques. We also propose Roofline performance models for these kernels to provide insights of computer platforms from sparse tensor view.","['cs.DC', 'cs.PF']",2020.0,NaN

In [27]:
text_columns = [
    "query",
    "source",
    "source_id",
    "title",
    "abstract",
    "doi",
    "url"
]

for col in text_columns:
    if col in df.columns:
        df[col] = df[col].apply(
            lambda x: x.strip()
            if isinstance(x, str)
            else x
        )

In [28]:
def normalize_doi(doi):

    if pd.isna(doi):
        return None

    doi = str(doi).strip().lower()

    doi = doi.replace(
        "https://doi.org/",
        ""
    )

    doi = doi.replace(
        "http://doi.org/",
        ""
    )

    doi = doi.replace(
        "doi:",
        ""
    )

    doi = doi.strip()

    return doi if doi else None

In [29]:
df["doi_normalized"] = df["doi"].apply(
    normalize_doi
)

In [30]:
df[
    ["doi", "doi_normalized"]
].head(10)

                          doi              doi_normalized
0          10.1002/smtd.71134          10.1002/smtd.71134
1           10.1111/cts.70742           10.1111/cts.70742
2          10.1002/acm2.70862          10.1002/acm2.70862
3  10.1186/s12913-026-15444-8  10.1186/s12913-026-15444-8
4  10.1007/s40520-026-03507-z  10.1007/s40520-026-03507-z
5                         NaN                         NaN
6                         NaN                         NaN
7                         NaN                         NaN
8                         NaN                         NaN
9                         NaN                         NaN

In [31]:
import re


def normalize_title(title):

    if pd.isna(title):
        return None

    title = str(title).lower().strip()

    title = re.sub(
        r"[^\w\s]",
        "",
        title
    )

    title = re.sub(
        r"\s+",
        " ",
        title
    )

    return title

In [32]:
df["title_normalized"] = df["title"].apply(
    normalize_title
)

In [33]:
df[
    ["title", "title_normalized"]
].head()

,title,title_normalized
0,Bionic Structural Design of Multifunctional Flexible Polypyrrole Sensors for Human Health Monitoring.,bionic structural design of multifunctional flexible polypyrrole sensors for human health monitoring
1,Clinical Decision Support Models to Optimize Controlled Ovarian Hyperstimulation: A Scoping Review.,clinical decision support models to optimize controlled ovarian hyperstimulation a scoping review
2,Machine learning predictors of post-radiotherapy cardiotoxicity in a Latin American breast cancer cohort: Clinical risk factors outperform cardiac dosimetry.,machine learning predictors of postradiotherapy cardiotoxicity in a latin american breast cancer cohort clinical risk factors outperform cardiac dosimetry
3,Mismatch between urban eco-sanitation improvement and health service supply capacity: evidence from Chinese city panel data and interpretable machine learning.,mismatch between urban ecosanitation improvement and health service supply capacity evidence from chinese city panel data and interpretable machine learning
4,Predicting Hospital-associated complications in older adults: methodological considerations.,predicting hospitalassociated complications in older adults methodological considerations

In [34]:
# DOI duplicates
doi_duplicates = df[
    df["doi_normalized"].notna()
    & df["doi_normalized"].duplicated(keep=False)
]

print(
    "Rows involved in DOI duplicates:",
    len(doi_duplicates)
)

Rows involved in DOI duplicates: 2

In [35]:
no_doi = df[
    df["doi_normalized"].isna()
].copy()

title_duplicates_no_doi = no_doi[
    no_doi["title_normalized"].notna()
    & no_doi["title_normalized"].duplicated(keep=False)
]

print(
    "Rows involved in title duplicates without DOI:",
    len(title_duplicates_no_doi)
)

Rows involved in title duplicates without DOI: 0

In [37]:
from pathlib import Path

Path("outputs").mkdir(exist_ok=True)

In [38]:
df.to_csv(
    "outputs/cleaned_papers.csv",
    index=False
)